* Linux basics

** check linux release

#+begin_src sh
cat /etc/*release*
#+end_src

** Linux Kernel

#+begin_src shell
# Display information about the kernel
uname

# get the kernel version
uname -r
6.1.0-23-amd64
#+end_src

- 6 = Kernel Version
- 1 = Major version
- 0 = Minor version
- 23 = patch releash
- amd64 = Distro specific info

Check [[https://kernel.org][kernel.org]] for more info

** Help in Linux

#+begin_src shell
# display a one line description of what a command does
whatis date

# display full help of a command
man date
date --help

# lookup all commands containing a specific part of text
apropos modpr
#+end_src

** Command types

- Internal or Built-in Commands =echo, cd, pwd, set etc=
- External Commands =mv, date, uptime, cp, uptime etc=
- Check the type of the command =type echo= =type mv=

** Basic Linux Commands

** Working with directories and files

#+begin_src sh
# create parent directories if not exist
mkdir -p India/Mumbai

# remember the current directory before moving to the next directory
~ pushd /etc
/etc ~
/etc ~ cd /var
/var ~ cd /tmp
/tmp ~ popd
~

# copy directory recursively
cp -r Europe/UK Europe/UnitedKingdom

# print contents of a file
cat dir/file1.txt

# redirect input to a file
cat > test.txt
# end input text and save it to the file
ctrl-d
#+end_src

** Linux Archive Files

#+begin_src sh
# create an archive
tar -cf test.tar file1 file2 file3

# view info of an archive
ls -ltr test.tar

# view the contents of a tarball
tar -tf test.tar

# extract the contents of a tarball
tar -xf test.tar

# create and compress an archive
tar -zcf test.tar file1 file2 file3
#+end_src

** List files

#+begin_src sh
# list files in order created
ls -lt
# list files in the reverse order created
ls -ltr
#+end_src

** Linux View File Size

#+begin_src sh
# inspect the size of a file
du test.img
du -sk test.img

# inspect the size of a file in a human readable format
du -sh test.img

# list files including their size
ls -lh
#+end_src

** Pages
- more
#+begin_src shell
more new_file.txt
#+end_src

#+begin_src md
# scroll the display one screenful of data at a time
SPC
# scroll the display one line
ENTER
# scroll the display backwords one screenfol of dsta
b
# search text
/
#+end_src

- more
#+begin_src shell
less new_file.txt
#+end_src

#+begin_src md
# scroll up the display one line
Up Arrow
# scroll down the display one line
Down Arrow
# search text
/
#+end_src
** [[file:Linux shell.org][Linux shell]]

** User acounts

#+begin_src shell

# get logged in user
whoami
# get more details for the user
id

# switch to another user
su <user>

#+end_src
*** Linux change owner

#+begin_src shell
sudo chown -R $USER /opt
#+end_src

*** The three permission groups in Linux, Kinds of permissions

| Letters | Definition                                                                  |
|---------+-----------------------------------------------------------------------------|
| 'r'     | "read" the file's contents.                                                 |
| 'w'     | "write", or modify, the file's contents.                                    |
| 'x'     | "execute" the file. This permission is given only if the file is a program. |
|         |                                                                             |

